In [1]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import LeaveOneOut
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import mean_squared_error, r2_score
import pandas as pd
from IPython.display import display
import random
from sklearn.metrics import recall_score, confusion_matrix, accuracy_score

In [2]:
df_tags = pd.read_csv(f"/data/foodboost/tags.csv", index_col = 0) 
df_recipes = pd.read_csv(f"/data/foodboost/recipes.csv")
df_nutritions = pd.read_csv(f"/data/foodboost/nutritions.csv", index_col = 0)
df_ingredients = pd.read_csv(f"/data/foodboost/ingredients.csv", index_col = 0)

In [3]:
df_tags

                                 recipe               tag
0         Kruidnoten met choco-discodip          hollands
1         Kruidnoten met choco-discodip             gebak
2         Kruidnoten met choco-discodip             gebak
3         Kruidnoten met choco-discodip       sinterklaas
4         Kruidnoten met choco-discodip  sinterklaasavond
...                                 ...               ...
46035                  Pittige truffels         nagerecht
46036  Biefstuk met rodewijnsaus en ham              snel
46037  Biefstuk met rodewijnsaus en ham       mediterraan
46038  Biefstuk met rodewijnsaus en ham      hoofdgerecht
46039  Biefstuk met rodewijnsaus en ham            bakken

[46040 rows x 2 columns]

In [4]:
listoftags = df_tags['tag'].unique().tolist()
list_of_recipes = df_tags['recipe'].unique().tolist()
tags = ['tags']

In [5]:
eten = pd.DataFrame(0,list_of_recipes, tags)
for i in range(len(df_tags)):
    a = df_tags.iloc[i][0]
    #print(a)
    b = df_tags.iloc[i][1]
    #print(b)
    index_recipe = list_of_recipes.index(a)
    #eten.iloc[index_recipe][1]='hoi'

In [6]:
eten

                                    tags
Kruidnoten met choco-discodip          0
Kruidnoten in marsepein                0
Kruidnoten met chocodips               0
Pepernotentaart met marsepeinstrik     0
Perencake                              0
...                                  ...
Paddenstoelen en courgettegratin       0
Peren-amandelcoupe                     0
Ceviche met sint-jakobsschelpen        0
Pittige truffels                       0
Biefstuk met rodewijnsaus en ham       0

[8705 rows x 1 columns]

In [7]:
df_tags

                                 recipe               tag
0         Kruidnoten met choco-discodip          hollands
1         Kruidnoten met choco-discodip             gebak
2         Kruidnoten met choco-discodip             gebak
3         Kruidnoten met choco-discodip       sinterklaas
4         Kruidnoten met choco-discodip  sinterklaasavond
...                                 ...               ...
46035                  Pittige truffels         nagerecht
46036  Biefstuk met rodewijnsaus en ham              snel
46037  Biefstuk met rodewijnsaus en ham       mediterraan
46038  Biefstuk met rodewijnsaus en ham      hoofdgerecht
46039  Biefstuk met rodewijnsaus en ham            bakken

[46040 rows x 2 columns]

In [8]:
df_tags.loc[df_tags['recipe'] == 'Biefstuk met rodewijnsaus en ham'].tag.to_list()

['snel', 'mediterraan', 'hoofdgerecht', 'bakken']

In [9]:
def tags_bij_recept(gerecht):
    a = df_tags.loc[df_tags['recipe'] == gerecht].tag.to_list()
    return a

In [10]:
tags_bij_recept('Biefstuk met rodewijnsaus en ham')

['snel', 'mediterraan', 'hoofdgerecht', 'bakken']

In [11]:
tags_bij_recept('Perencake')

['vooraf te maken', 'oven', 'gebak', 'gebak']

In [12]:
def recepten_bij_tag(tag):
    a = df_tags.loc[df_tags['tag'] == tag].recipe.to_list()
    return a
def tags_bij_recept(gerecht):
    a = df_tags.loc[df_tags['recipe'] == gerecht].tag.to_list()
    return a

In [13]:
hollands = random.sample(recepten_bij_tag('hollands'), 8)
mexicaans = random.sample(recepten_bij_tag('mexicaans'), 8)

In [14]:
def unieke_platte_lijst(gerechten_lijst):
    list_of_tags = []
    for i in gerechten_lijst:
        list_of_tags.append(tags_bij_recept(i))
    flatten = list(np.concatenate(list_of_tags).flat)
    flatten = np.unique(np.array(flatten))
    return flatten

In [15]:
lijst = unieke_platte_lijst(hollands)

In [16]:
lijst

array(['5-ingrediënten', 'bakken', 'barbecue', 'bijgerecht', 'borrel',
       'borrelhapje', 'brunch', 'budget', 'gebak', 'glutenvrij',
       'hollands', 'hoofdgerecht', 'kindergerecht', 'kinderrecepten',
       'koken', 'lactosevrij', 'lunch', 'moederdag', 'ontbijt', 'oven',
       'picknick', 'salade', 'sinterklaas', 'sinterklaasavond', 'soep',
       'stamppot', 'traktatie', 'tussendoortje', 'vaderdag',
       'veganistisch', 'vegetarisch', 'vooraf te maken', 'voorgerecht',
       'wat eten we vandaag', 'zonder vlees/vis'], dtype='<U19')

In [17]:
for i in lijst:
    print(i)

5-ingrediënten
bakken
barbecue
bijgerecht
borrel
borrelhapje
brunch
budget
gebak
glutenvrij
hollands
hoofdgerecht
kindergerecht
kinderrecepten
koken
lactosevrij
lunch
moederdag
ontbijt
oven
picknick
salade
sinterklaas
sinterklaasavond
soep
stamppot
traktatie
tussendoortje
vaderdag
veganistisch
vegetarisch
vooraf te maken
voorgerecht
wat eten we vandaag
zonder vlees/vis

In [18]:
frame = pd.DataFrame(0, range(1,17), listoftags)

In [19]:
y = [1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0]
len(y)

16

In [20]:
frame3 = pd.DataFrame(y,range(1,17), range(1))

In [21]:
frame3 = frame3.rename(columns={0: "y"})

In [22]:
#frame1 is voor de 8 
frame1 = pd.DataFrame(0, range(1,17), listoftags)
frame2 = pd.DataFrame(0, range(1,17), listoftags)

In [23]:
pd.concat([frame1, frame2, frame3],keys=['frame1', 'frame2', 'y'],  axis=1)

     frame1                                                          \
   hollands gebak sinterklaas sinterklaasavond oven vooraf te maken
1         0     0           0                0    0               0
2         0     0           0                0    0               0
3         0     0           0                0    0               0
4         0     0           0                0    0               0
5         0     0           0                0    0               0
6         0     0           0                0    0               0
7         0     0           0                0    0               0
8         0     0           0                0    0               0
9         0     0           0                0    0               0
10        0     0           0                0    0               0
11        0     0           0                0    0               0
12        0     0           0                0    0               0
13        0     0           0                0    0               0
14        0     0           0                0    0               0
15        0     0           0                0    0               0
16        0     0           0                0    0               0

                                      ...     frame2                \
   lactosevrij thais aziatisch curry  ... slowcooker oost-europees
1            0     0         0     0  ...          0             0
2            0     0         0     0  ...          0             0
3            0     0         0     0  ...          0             0
4            0     0         0     0  ...          0             0
5            0     0         0     0  ...          0             0
6            0     0         0     0  ...          0             0
7            0     0         0     0  ...          0             0
8            0     0         0     0  ...          0             0
9            0     0         0     0  ...          0             0
10           0     0         0     0  ...          0             0
11           0     0         0     0  ...          0             0
12           0     0         0     0  ...          0             0
13           0     0         0     0  ...          0             0
14           0     0         0     0  ...          0             0
15           0     0         0     0  ...          0             0
16           0     0         0     0  ...          0             0

                                                                   \
   valentijnsdag zuid-afrikaans koreaans kidsfavoriet diner lente
1              0              0        0            0     0     0
2              0              0        0            0     0     0
3              0              0        0            0     0     0
4              0              0        0            0     0     0
5              0              0        0            0     0     0
6              0              0        0            0     0     0
7              0              0        0            0     0     0
8              0              0        0            0     0     0
9              0              0        0            0     0     0
10             0              0        0            0     0     0
11             0              0        0            0     0     0
12             0              0        0            0     0     0
13             0              0        0            0     0     0
14             0              0        0            0     0     0
15             0              0        0            0     0     0
16             0              0        0            0     0     0

                 y
   jamie oliver  y
1             0  1
2             0  0
3             0  1
4             0  0
5             0  1
6             0  0
7             0  1
8             0  0
9             0  1
10            0  0
11            0  1
12            0  0
13            0  1
14            0  0
15            0  1
16            0  0

[16 rows x 237 columns]

In [24]:
def recepten_zonder(tag):
    return [x for x in list_of_recipes if x not in recepten_bij_tag(tag)]

In [25]:
random8_recepten = random.sample(recepten_zonder('hollands'), 8)

In [26]:
random8_recepten

['Couscoussalade met gegrilde groenten, hummus en witte kaas',
 'Gevuld brood met champignonragout',
 'Kerstrol met Griekse yoghurt',
 'Bananen-notenbrood',
 'Hertenbiefstuk met cranberrysaus',
 'Vitaminedino',
 'Zomerquiche met rode ui, ricotta en peterselieolie',
 'Thaise kokossoep met kip en noedels']

In [27]:
hollands

['Frisse aardappelsalade',
 'Pepernoten',
 'Wentelteefjes met ahornsiroop en spek',
 'Crèmesoep van schorseneren',
 'Pepernoten zonder zuivel',
 'Ingemaakte mini-komkommers ',
 'Preistamppot met zoete aardappel, Amsterdamse ui en varkensbraadworst',
 'Spruitjesgratin met zoete aardappel']

In [28]:
frame1

,hollands,gebak,sinterklaas,sinterklaasavond,oven,vooraf te maken,lactosevrij,thais,aziatisch,curry,...,mealprep,slowcooker,oost-europees,valentijnsdag,zuid-afrikaans,koreaans,kidsfavoriet,diner,lente,jamie oliver
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [29]:
hollands_lijst = []
for i in hollands:
    hollands_lijst.append(tags_bij_recept(i))

In [30]:
frame1extra = pd.DataFrame({'LOO':[1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8]}, range(1,17))

In [31]:
frame1extra

    LOO
1     1
2     1
3     2
4     2
5     3
6     3
7     4
8     4
9     5
10    5
11    6
12    6
13    7
14    7
15    8
16    8

In [32]:
for i in range(len(frame1extra)):
    print(frame1extra.iloc[i][0])

1
1
2
2
3
3
4
4
5
5
6
6
7
7
8
8

In [33]:
hollands_lijst

[['vegetarisch',
  'glutenvrij',
  'lactosevrij',
  'vooraf te maken',
  'hollands',
  'salade',
  'lunch',
  'bijgerecht',
  'picknick',
  'barbecue',
  'wat eten we vandaag',
  'koken'],
 ['lactosevrij',
  'vooraf te maken',
  'oven',
  'hollands',
  'gebak',
  'gebak',
  'kindergerecht',
  'sinterklaasavond',
  'sinterklaas',
  'kinderrecepten'],
 ['hollands',
  'ontbijt',
  'brunch',
  'moederdag',
  'vaderdag',
  'bakken',
  'kinderrecepten'],
 ['vegetarisch',
  'hollands',
  'soep',
  'voorgerecht',
  'wat eten we vandaag',
  'koken'],
 ['lactosevrij',
  'veganistisch',
  'oven',
  'hollands',
  'gebak',
  'gebak',
  'sinterklaas',
  'traktatie'],
 ['glutenvrij',
  'lactosevrij',
  'vooraf te maken',
  'hollands',
  'tussendoortje',
  'borrelhapje',
  'bijgerecht',
  'borrel'],
 ['glutenvrij',
  'budget',
  'hollands',
  'stamppot',
  'hoofdgerecht',
  'wat eten we vandaag',
  'koken'],
 ['zonder vlees/vis',
  'oven',
  'hollands',
  'hoofdgerecht',
  'wat eten we vandaag',
  '5-ingrediënten']]

In [34]:
df_ingredients

,recipe,ingredient,quantity,unit
0,Kruidnoten met choco-discodip,melkchocolade,100.0,g
1,Kruidnoten met choco-discodip,kruidnoten,100.0,g
2,Kruidnoten met choco-discodip,discodip,2.0,el
3,Kruidnoten in marsepein,blanke marsepein,150.0,g
4,Kruidnoten in marsepein,ongezouten roomboter,15.0,g
...,...,...,...,...
71804,Biefstuk met rodewijnsaus en ham,olijfolie,4.0,el
71805,Biefstuk met rodewijnsaus en ham,biefstukken,4.0,NaN
71806,Biefstuk met rodewijnsaus en ham,boter,25.0,g
71807,Biefstuk met rodewijnsaus en ham,serranoham,4.0,plakken
71808,Biefstuk met rodewijnsaus en ham,rode wijn,200.0,ml

In [35]:
df_ingredients.iloc[2][1]

'discodip'

In [36]:
def ingredienten_bij_recept(gerecht):
    a = df_ingredients.loc[df_ingredients['recipe'] == gerecht].ingredient.to_list()
    return a

In [37]:
ingredienten_bij_recept('Perencake')

['middelgroot ei',
 'Griekse yoghurt 10%',
 'fijne kristalsuiker',
 'vanille-extract',
 'zonnebloemolie',
 'tarwebloem',
 'bakpoeder',
 'zout',
 'Conference peer']

In [38]:
list_of_ingredients = df_ingredients['ingredient'].unique().tolist()

In [39]:
len(list_of_ingredients)

7204

In [40]:
lijst20 = []
for i in hollands:
    lijst20.append(ingredienten_bij_recept(i))

In [41]:
flatten = list(np.concatenate(lijst20).flat)
flatten = np.unique(np.array(flatten))

In [42]:
len(flatten)

53

In [43]:
lijst = []
for i in listoftags:
    lijst.append(len(recepten_bij_tag(i)))

In [44]:
lijst

[827,
 1291,
 86,
 88,
 2542,
 1250,
 1923,
 77,
 822,
 71,
 4595,
 1588,
 1679,
 267,
 112,
 573,
 627,
 1118,
 283,
 199,
 500,
 72,
 398,
 2768,
 505,
 243,
 131,
 1277,
 1435,
 1,
 1495,
 46,
 110,
 1071,
 762,
 848,
 216,
 289,
 423,
 380,
 239,
 762,
 114,
 789,
 435,
 649,
 144,
 46,
 60,
 437,
 304,
 86,
 347,
 25,
 191,
 225,
 717,
 20,
 124,
 206,
 557,
 16,
 1,
 175,
 105,
 375,
 9,
 649,
 620,
 7,
 379,
 346,
 45,
 482,
 352,
 150,
 25,
 94,
 29,
 159,
 210,
 83,
 104,
 93,
 221,
 6,
 107,
 248,
 4,
 1,
 1,
 73,
 8,
 1,
 4,
 6,
 17,
 1,
 1,
 39,
 147,
 32,
 323,
 14,
 60,
 46,
 348,
 130,
 4,
 9,
 10,
 33,
 1,
 5,
 1,
 150,
 6,
 10]

In [45]:
recepten_bij_tag('jamie oliver')

['Frittata met lentegroenten',
 'Gemengde geroosterde groenten',
 'Simpele kaasfondue',
 'Semifreddo met snickers',
 'Chocolade-kardemomcake',
 'Romige paddenstoelensoep',
 'Amuse zalm op een vorkje',
 'Eenvoudige rodekool',
 'Spi\xadna\xadzie-ri\xadcot\xadta\xadro\xadto\xadlo',
 'Wellington van rundergehakt']

In [46]:
len(recepten_bij_tag('hoofdgerecht'))

4595

In [47]:
df_ingredients

,recipe,ingredient,quantity,unit
0,Kruidnoten met choco-discodip,melkchocolade,100.0,g
1,Kruidnoten met choco-discodip,kruidnoten,100.0,g
2,Kruidnoten met choco-discodip,discodip,2.0,el
3,Kruidnoten in marsepein,blanke marsepein,150.0,g
4,Kruidnoten in marsepein,ongezouten roomboter,15.0,g
...,...,...,...,...
71804,Biefstuk met rodewijnsaus en ham,olijfolie,4.0,el
71805,Biefstuk met rodewijnsaus en ham,biefstukken,4.0,NaN
71806,Biefstuk met rodewijnsaus en ham,boter,25.0,g
71807,Biefstuk met rodewijnsaus en ham,serranoham,4.0,plakken
71808,Biefstuk met rodewijnsaus en ham,rode wijn,200.0,ml

In [48]:
list_of_ingredients = df_ingredients['ingredient'].unique().tolist()

In [49]:
diner_set1 = set(recepten_bij_tag('hoofdgerecht')) 
diner_set2 = set(recepten_bij_tag('diner')) 
diner = diner_set1.union(diner_set2)

In [50]:
kleine_df = df_ingredients[df_ingredients['recipe'].isin(diner)]

In [51]:
list_of_ingredients = kleine_df['ingredient'].unique().tolist()

In [52]:
len(list_of_ingredients)

5006

In [53]:
teller = kleine_df.groupby(['ingredient']).recipe.count().to_frame()

In [54]:
teller

                         recipe
ingredient
(arachide)olie               80
(herten)biefstukken           1
(houdbare) melk               1
(magere) shoarmareepjes       1
(olijf)olie                 107
...                         ...
zwarte-peperkorrel            1
zwarte-peperkorrels           5
zwarteolijvenplakjes          1
zwartepeperkorrel             2
zwijnsteak                    1

[5006 rows x 1 columns]

In [55]:
print(teller[teller['recipe'] == 1])
#minimaal even groot als K
ingredients_Boven_K = teller[teller['recipe'] > 20].index

                         recipe
ingredient
(herten)biefstukken           1
(houdbare) melk               1
(magere) shoarmareepjes       1
(wilde) perzik                1
(witte) quinoa                1
...                         ...
zwarte sesamzaadje            1
zwarte tagliatelle            1
zwarte-peperkorrel            1
zwarteolijvenplakjes          1
zwijnsteak                    1

[2298 rows x 1 columns]

In [56]:
ingredients_Boven_K

Index(['(arachide)olie', '(olijf)olie', '1 minuut basmatirijst',
       'Catalaanse braadworst', 'Cheddar Tophat 48+', 'Chinese eiermie',
       'Elstar appel', 'Euroma Original Spices by Jonnie Boer picadillo',
       'Franse mosterd', 'Griekse yoghurt',
       ...
       'zeezout', 'zilvervliesrijst', 'zoete aardappel', 'zoete chilisaus',
       'zoete puntpaprika', 'zonnebloemolie', 'zout', 'zure room',
       'zwarte bonen', 'zwarte bonen in blik'],
      dtype='object', name='ingredient', length=341)

In [57]:
Matrix = pd.DataFrame(0, range(0,15), ingredients_Boven_K)

In [58]:
Matrix

ingredient,(arachide)olie,(olijf)olie,1 minuut basmatirijst,Catalaanse braadworst,Cheddar Tophat 48+,Chinese eiermie,Elstar appel,Euroma Original Spices by Jonnie Boer picadillo,Franse mosterd,Griekse yoghurt,...,zeezout,zilvervliesrijst,zoete aardappel,zoete chilisaus,zoete puntpaprika,zonnebloemolie,zout,zure room,zwarte bonen,zwarte bonen in blik
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [59]:
ingredienten_bij_recept('Perencake')

['middelgroot ei',
 'Griekse yoghurt 10%',
 'fijne kristalsuiker',
 'vanille-extract',
 'zonnebloemolie',
 'tarwebloem',
 'bakpoeder',
 'zout',
 'Conference peer']

In [60]:
df_nutritions[df_nutritions['nutrition']=='energie']

                                   recipe nutrition     value
0           Kruidnoten met choco-discodip   energie  260 kcal
8                 Kruidnoten in marsepein   energie  265 kcal
16               Kruidnoten met chocodips   energie  335 kcal
24     Pepernotentaart met marsepeinstrik   energie  560 kcal
32                              Perencake   energie  265 kcal
...                                   ...       ...       ...
58742    Paddenstoelen en courgettegratin   energie  285 kcal
58747                  Peren-amandelcoupe   energie  160 kcal
58751     Ceviche met sint-jakobsschelpen   energie  210 kcal
58756                    Pittige truffels   energie   65 kcal
58761    Biefstuk met rodewijnsaus en ham   energie  360 kcal

[8706 rows x 3 columns]

In [61]:
df_nutritions['nutrition'].unique().tolist()

['energie',
 'koolhydraten',
 'waarvan suikers',
 'natrium',
 'eiwit',
 'vet',
 'waarvan verzadigd',
 'vezels']

In [62]:
df_ingredients[df_ingredients['ingredient']=='witte peper']

                                       recipe   ingredient  quantity unit
77                               Ajam pangang  witte peper      1.00   tl
3191                     Vietnamese loempia's  witte peper      0.25   tl
3799     Zalm van de BBQ met zelfgemaakte rub  witte peper      1.00   el
40282  Wontons met varkensvlees en boerenkool  witte peper      0.25   tl
54747                       Paksoi met gehakt  witte peper      2.00   tl
55103        Radijssalade met zwart sesamzaad  witte peper      0.50   tl

In [63]:
kleine_df[kleine_df['ingredient']=='halfvolle melk']

,recipe,ingredient,quantity,unit
246,Andijviestamppot met tomaatjes en zalm,halfvolle melk,200.0,ml
440,Wilde rijstsoep met kip,halfvolle melk,250.0,ml
555,"Stamppot boerenkool met geroosterde pompoen, s...",halfvolle melk,150.0,ml
634,Ovenschotel met chipolata en knolselderij,halfvolle melk,1.0,liter
2361,Gegratineerde orzo met champignons en broccoli...,halfvolle melk,400.0,ml
...,...,...,...,...
71413,Balletjes met fruit,halfvolle melk,75.0,ml
71549,Italiaans-Amerikaanse lasagne,halfvolle melk,700.0,ml
71644,Zweedse gehaktballetjes,halfvolle melk,100.0,ml
71683,Ovenpasta met tomaat,halfvolle melk,250.0,ml
71736,Tijmballetjes met puree,halfvolle melk,100.0,ml

In [66]:
df_tags[df_tags['recipe'].isin(diner)].tag.unique().tolist()[:20]

['lactosevrij',
 'thais',
 'aziatisch',
 'curry',
 'hoofdgerecht',
 'koken',
 'glutenvrij',
 'oven',
 'frans',
 'indonesisch',
 'hollands',
 'wat eten we vandaag',
 'chinees',
 'frituren',
 'vegetarisch',
 'italiaans',
 'pasta',
 'bakken',
 'snel',
 'stamppot']

In [67]:
len(recepten_bij_tag('borrelhapje'))

573